cluster_domain = "taishan.website"

[nats]
hosts = [
  "52.23.71.102"
]

[agent]

  [agent.ip]
  api = "http://ip-api:8080/"

  [agent.docker]
  network = "plane"

    [agent.docker.connection]
    socket = "/var/run/docker.sock"

[proxy]
bind_ip = "0.0.0.0"
http_port = 8080.0
allow_path_routing = false